/** Single source of truth for URLs. Never hard-code a path in a component. */
export const routePaths = {
  root: '/',
  registration: '/registration',
  customerType: '/customer-type',
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    otp: '/auth/otp',
    passcode: '/auth/passcode',
    createProfile: '/auth/create-profile',
    customerType: '/auth/customer-type',
  },
  dashboard: '/dashboard',
  gst: {
    root: '/gst',
    registration: '/gst/registration',
    returns: '/gst/returns',
    filing: '/gst/filing',
    filePeriod: '/gst/file-period',
    fileUpload: '/gst/file-upload',
    fileReview: '/gst/file-review',
    filePayment: '/gst/file-payment',
    fileSuccess: '/gst/file-success',
    fileReceipt: '/gst/file-receipt',
    detail: (id = ':id') => `/gst/${id}`,
    track: (id = ':id') => `/gst/${id}/track`,
  },
  itr: '/itr',
  loans: '/loans',
  insurance: '/insurance',
  payments: '/payments',
  paymentReceipt: (id = ':id') => `/payments/receipt/${id}`,
  paymentReceiptDirect: '/payments/receipt',
  documents: '/documents',
  applications: '/applications',
  services: '/services',
  allServices: '/all-services',
  profile: '/profile',
  chat: '/chat',
  support: '/support',
  staff: {
    root: '/staff',
    dashboard: '/staff/dashboard',
    applications: '/staff/applications',
    applicationDetail: (id = ':applicationId') => `/staff/applications/${id}`,
    customers: '/staff/customers',
    customerDetail: (id = ':customerId') => `/staff/customers/${id}`,
    assignments: '/staff/assignments',
    documents: '/staff/documents',
    reports: '/staff/reports',
    staffManagement: '/staff/staff-management',
    services: '/staff/services',
    pricing: '/staff/pricing',
    notifications: '/staff/notifications',
    settings: '/staff/settings',
  },
  notFound: '*',
} as const
